{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Main View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live View",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT\r\n  time,\r\n  latitude AS latitude_last,\r\n  longitude AS longitude_last,\r\n  ground_heading_deg * 100000 AS ground_heading_deg\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time DESC\r\nLIMIT 1\r\n"
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT\r\n  time,\r\n  latitude,\r\n  longitude,\r\n  carrier_phase_range_int\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Rover Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  latitude,\r\n  horizontal_accuracy_m\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Live View",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  latitude AS latitude_last,\r\n  longitude AS longitude_last,\r\n  ground_heading_deg * 100000 AS ground_heading_deg\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time DESC\r\nLIMIT 1\r\n"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  latitude,\r\n  longitude,\r\n  carrier_phase_range_int\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  altitude_m,\r\n  altitude_m + vertical_accuracy_m AS upper_bound,\r\n  altitude_m - vertical_accuracy_m AS lower_bound\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  ground_speed_ms,\r\n  ground_speed_ms + speed_accuracy_ms AS upper_bound,\r\n  GREATEST(ground_speed_ms - speed_accuracy_ms, 0) AS lower_bound\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time) \r\nORDER BY\r\n  time"
    }
   ]
  },
  {
   "title": "Fix Valid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  fix_ok_int\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) AND fix_ok_int IS NOT NULL\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Fix Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  fix_type_int\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) AND fix_type_int IS NOT NULL\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "NTRIP Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  ntrip_client_rtcm_received_int\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) AND ntrip_client_rtcm_received_int IS NOT NULL\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "RTK Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  carrier_phase_range_int\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) AND carrier_phase_range_int IS NOT NULL\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Correction Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  last_correction_age_int\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) AND last_correction_age_int IS NOT NULL\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Line of Sight (% of expected satellites visible)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_tracked,\n  num_sats_visible\nFROM\n  station_telemetry\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "GNSS-Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Satellites" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_code_locked\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "RTK-Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Satellites" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_carrier_locked\nFROM\n  metrics\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  { "title": "Basestation Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Line of Sight (% of expected satellites visible)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_tracked,\n  num_sats_visible\nFROM\n  station_telemetry\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "GNSS-Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Satellites" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_code_locked\nFROM\n  station_telemetry\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  latitude AS latitude_last,\r\n  longitude AS longitude_last\r\nFROM\r\n  station_telemetry\r\nWHERE\r\n  $__timeFilter(time) AND latitude IS NOT NULL\r\nORDER BY\r\n  time DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "RTK-Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Satellites" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  num_sats_carrier_locked\nFROM\n  station_telemetry\nWHERE\n  $__timeFilter(time) \nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Network Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {}
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT\n  time,\n  id::BIGINT,\n  vpn_ip,\n  group_name,\n  id::BIGINT as Actions,\n  ping,\n  ping AS ping_avg,\n  ping AS ping_trend\nFROM network_telemetry\nWHERE $__timeFilter(time) AND ping IS NOT NULL\nORDER BY time ASC"
      }
     ]
    }
   ]
  }
 ]
}