{
 "title": "Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "First Degree Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  altitude_m\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time"
    },
    { "expression": "$value+ ($acc)/2\n", "type": "math" },
    { "expression": "$value- ($acc)/2\n", "type": "math" }
   ]
  },
  {
   "title": "Live View",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  latitude,\r\n  longitude\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  ground_speed_ms\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time"
    },
    { "expression": "$value+ ($acc)/2\n", "type": "math" },
    { "expression": "$value- ($acc)/2\n", "type": "math" }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  horizontal_accuracy_m\r\nFROM\r\n  metrics\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time\r\n"
    }
   ]
  }
 ]
}