FROM python:3.10-slim
COPY requirements.txt /home/ntrip-client/requirements.txt
WORKDIR /home/ntrip-client
RUN pip install --no-cache-dir -r requirements.txt
COPY . /home/ntrip-client
CMD ["python", "-u", "app.py", "personal"]