FROM python:3.9-slim

WORKDIR /home/enrollment-client

COPY . /home/enrollment-client

COPY ../../.env /home/enrollment-client/.env

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]