apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: ${INFLUXDB_HOST}
    jsonData:
      version: SQL
      dbName: GPS
      httpMode: POST
      insecureGrpc: false
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true