FROM python:3.10-slim
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /home/enrollment-server/requirements.txt
WORKDIR /home/enrollment-server
RUN pip install --no-cache-dir -r requirements.txt
COPY . /home/enrollment-server
CMD ["python", "run.py"]