FROM python:3.10-slim
WORKDIR /home/enrollment-server
COPY . /home/enrollment-server
COPY --from=common . /home/enrollment-server/common
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*
CMD ["python", "run.py"]