services:
  enrollment-server:
    build: ./enrollment-server
    # image: polaris/enrollment-server:latest  # FOR FINAL DELIVERABLE
    container_name: enrollment-server
    environment:
      - LIGHTHOUSE_HOSTNAME=${LIGHTHOUSE_HOSTNAME}  
      - LIGHTHOUSE_ADMIN_PASSWORD=${LIGHTHOUSE_ADMIN_PASSWORD}
    volumes:
      - ./shared:/home/enrollment-server/shared
    restart: unless-stopped
  nebula:
    image: nebulaoss/nebula:latest
    container_name: nebula
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./shared:/config
    depends_on:
      - enrollment-server
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${LIGHTHOUSE_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${LIGHTHOUSE_ADMIN_PASSWORD}
      - INFLUXDB_HOST=https://${LIGHTHOUSE_HOSTNAME}/influx
      - INFLUXDB_TOKEN=apiv3_${LIGHTHOUSE_ADMIN_PASSWORD}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard_provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    restart: unless-stopped
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    environment:
      - INFLUX_TOKEN=apiv3_${LIGHTHOUSE_ADMIN_PASSWORD}
    ports:
      - "8181:8181"
    volumes:
      - ./influxdb/data:/var/lib/influxdb3/data
      - ./influxdb/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: unless-stopped
  influxdb-explorer:
    image: influxdata/influxdb3-ui:1.3.0
    container_name: influxdb-explorer
    volumes:
      - ./influxdb/config:/app-root/config:ro
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - LIGHTHOUSE_HOSTNAME=${LIGHTHOUSE_HOSTNAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx/templates:/etc/nginx/templates
    command: "nginx -g 'daemon off;'"
    depends_on:
      - enrollment-server
      - grafana
      - influxdb
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
