services:
  enrollment-server:
    build: ./enrollment-server
    # image: polaris/enrollment-server:latest  # FOR FINAL DELIVERABLE
    container_name: enrollment-server
    volumes:
      - ./shared:/home/enrollment-server/shared
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    restart: unless-stopped
  nebula:
    image: nebulaoss/nebula:latest
    container_name: nebula
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./shared:/config
    depends_on:
      - enrollment-server
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-config/dashboards:/var/lib/grafana/dashboards
      - ./grafana-config/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-config/dashboard_provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    ports:
      - "3000:3000"
    restart: unless-stopped