services:
  enrollment-server:
    build: ./enrollment-server
    # image: polaris/enrollment-server:latest  # FOR FINAL DELIVERABLE
    container_name: enrollment-server
    volumes:
      - ./shared:/home/enrollment-server/shared
    restart: unless-stopped
  nebula:
    image: nebulaoss/nebula:latest
    container_name: nebula
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./shared:/config
    depends_on:
      - enrollment-server
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - LIGHTHOUSE_PUBLIC_IP=${LIGHTHOUSE_PUBLIC_IP}  
      - LIGHTHOUSE_NETWORK_KEY=${LIGHTHOUSE_NETWORK_KEY}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard_provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    restart: unless-stopped
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: 'nginx -g "daemon off;"'
    depends_on:
      - enrollment-server
      - grafana
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"