services:

  enrollment-client:
    build: ../lighthouse/enrollment-client
    # image: polaris/enrollment-client:latest
    container_name: enrollment-client
    volumes:
      - ./shared:/home/enrollment-client/shared
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    restart: unless-stopped

  nebula:
    image: nebulaoss/nebula:latest
    container_name: nebula
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./shared:/etc/nebula
    depends_on:
      - enrollment-client
    restart: unless-stopped