FROM python:3.10-slim
COPY requirements.txt /home/ntrip-caster/requirements.txt
WORKDIR /home/ntrip-caster
RUN pip install --no-cache-dir -r requirements.txt
COPY . /home/ntrip-caster
CMD ["python", "-u", "app.py"]